ftp:
  host: 150.158.150.182
  userName: root
  password: Wzb1999616@
  port: 22
  rootPath: /mydata/nginx/html/video/
  img:
    url: http://150.158.150.182:80/video  # ftp.img.url 可以不添加，这里只是为了上传文件成功后返回文件路径